consensus_node:
    block_interval: 2000
    block_record_dir: exp/agentemu-results/round_001/chain/data/block_record
    blockchain:
        bloom_filter:
            bitset_len: 4096
            filter_hash_func:
                - sha256
                - sha512
                - sha1
        storage:
            block_storage_type: bolt
            bolt:
                file_path_dir: exp/agentemu-results/round_001/chain/data/boltdb
            eth_storage:
                is_memory_db: false
                level_file_path_dir: exp/agentemu-results/round_001/chain/data/trie_db
                old_state_root: ""
            trie_storage_type: eth_level_db
    tx_pool:
        type: number
network:
    bandwidth: 1000000
    communication_mode: direct
    latency: 0
    libp2p:
        bootstrap_ip: 127.0.0.1
        bootstrap_key_fp: ./pkg/network/connlibp2p/bootstrap.key
        bootstrap_peer: 12D3KooWR6siPMZ2sMFKbgwaJFwQfnKczuPZnxHfyy1dHTzZSAUY
        bootstrap_port: 12345
supervisor:
    broker_module:
        broker_file_path: ./pkg/broker/broker
        broker_num: 50
    epoch_duration: 50
    result_output_dir: exp/agentemu-results/round_001/chain/results
    tx_injection_speed: 20000
    tx_number: 48
    tx_source:
        exclude_contract_txs: false
        tx_source_file: /Users/baozhouxie/agent-emulator/exp/agentemu-results/round_001/agent_transactions.jsonl
        tx_source_type: trace_source_JSONL
system:
    consensus_type: static_relay
    limit: 5000
    log:
        log_dir: exp/agentemu-results/round_001/chain/logs
        log_level: info
    node_num: 4
    shard_num: 4
